import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";
import Providers from "@/redux/features/Providers";
import { Toaster } from "sonner";
import Chatbot from "@/components/message/Message";

const plusJakartaSans = Plus_Jakarta_Sans({
  variable: "--font-plus-jakarta-sans",
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "Veluxa Clean",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' upword-verified='true'>
      <body
        className={`${plusJakartaSans.variable} antialiased`}
        style={{ fontFamily: "var(--font-plus-jakarta-sans)" }}
        suppressHydrationWarning
      >
        <Providers>
          <Toaster position='top-center' />
          <Navbar />
          {children}
          <Footer />
        </Providers>
        <Chatbot />
      </body>
    </html>
  );
}
